### ISSUE TITLE
Time zone issues in DOMserver docker image

### ISSUE THREAD

**Issue by Dup4** [DOMjudge/domjudge-packaging#100]
In the [README](https://github.com/DOMjudge/domjudge-packaging/blob/95ffd1053678454e89635bad42eb3530b9f71a46/docker/README.md?plain=1#L77
), pointed out that is can be passed `CONTAINER_TIMEZONE` to set system time zone.

https://github.com/DOMjudge/domjudge-packaging/blob/95ffd1053678454e89635bad42eb3530b9f71a46/docker/README.md#L77

[During container startup](https://github.com/DOMjudge/domjudge-packaging/blob/95ffd1053678454e89635bad42eb3530b9f71a46/docker/domserver/scripts/start.d/10-timezone.sh#L3-L6), this did change the time zone of the system.

https://github.com/DOMjudge/domjudge-packaging/blob/95ffd1053678454e89635bad42eb3530b9f71a46/docker/domserver/scripts/start.d/10-timezone.sh#L3-L6

But during the image building process, the default time zone setting of php is changed through `CONTAINER_TIMEZONE`.

https://github.com/DOMjudge/domjudge-packaging/blob/95ffd1053678454e89635bad42eb3530b9f71a46/docker/domserver/configure.sh#L37-L42

So if we pass in `CONTAINER_TIMEZONE` when the container is started, it will not change the default time zone of php, which will cause the relevant time zone in the DOMserver to not meet expectations.

So I suggest adding a replacement for the time zone in `php.ini` in [`docker/domserver/scripts/start.d/10-timezone.sh`](https://github.com/DOMjudge/domjudge-packaging/blob/main/docker/domserver/scripts/start.d/10-timezone.sh)

If this proposal is passed, I can make corresponding changes.

**Comment by nickygerritsen** [comment]
Sounds good. PR indeed welcome
