### ISSUE TITLE
Bugfix some errors in scripts

### ISSUE THREAD

**Issue by Dup4** [DOMjudge/domjudge-packaging#104]
https://github.com/DOMjudge/domjudge-packaging/blob/b7ebf8f02ec8e0014a595d9c8bfacf4e3db8982f/docker/domserver/configure.sh#L15-L22

![image](https://user-images.githubusercontent.com/38343778/143727261-48218cc9-c39d-4cc6-a81a-c59302aef27d.png)

https://github.com/koalaman/shellcheck/wiki/SC2066

![image](https://user-images.githubusercontent.com/38343778/143727317-1afce45a-37ad-49d7-9553-879004858f0a.png)

Obviously, the code in the loop has not taken offect.

https://github.com/DOMjudge/domjudge-packaging/blob/b7ebf8f02ec8e0014a595d9c8bfacf4e3db8982f/docker/domserver/configure.sh#L64-L65

![image](https://user-images.githubusercontent.com/38343778/143727290-bb9f8710-9b11-4099-a7ca-fdaa2ed05b04.png)

https://github.com/koalaman/shellcheck/wiki/SC2016

![image](https://user-images.githubusercontent.com/38343778/143727348-84044bf7-0cc4-49f8-b9f5-40c739eec1ee.png)

`${php_version}` replacement was not successful.

https://github.com/DOMjudge/domjudge-packaging/blob/b7ebf8f02ec8e0014a595d9c8bfacf4e3db8982f/docker/judgehost/build.sh#L9

![image](https://user-images.githubusercontent.com/38343778/143727488-35ec05c0-c087-4250-9c16-f3566dfcd193.png)

https://github.com/koalaman/shellcheck/wiki/SC2024

**Comment by Dup4** [comment]
BTW: I detected these errors by using [shellcheck in vscode](https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck).

- And [shellcheck](https://github.com/koalaman/shellcheck) can also be run by GitHub Actions.
- https://github.com/marketplace/actions/shellcheck
- So do we consider adding the Actions in this repo, so that some errors can be detected in the PR phase, and it is convenient for the Reviewer to perform Code Review.
- But I noticed that you mainly use gitlab CI, so I don't know what you think.
- Or you can add related check in Gitlab CI.
- After all, our goal is to eliminate errors, it has nothing to do with which platform is used, right?

**Comment by nickygerritsen** [comment]
Our main repo has some GitHub actions now. I leave it to @vmcj to think where to place shellcheck

**Comment by vmcj** [comment]
@Dup4 I've added shellcheck, so let's see what it can find besides your fixes.

**Comment by Dup4** [comment]
![image](https://user-images.githubusercontent.com/38343778/143764170-0894ec80-45e8-440c-8431-dcbd66a835b1.png)

good job. @vmcj 

Looks like some issues have been detected

**Comment by nickygerritsen** [comment]
I think we can close this issue now by the way?

**Comment by Dup4** [comment]
> I think we can close this issue now by the way?

Yes.
