### ISSUE TITLE
When I uploaded the banner, a 500 Internal Server Error occurred

### ISSUE THREAD

**Issue by Dup4** [DOMjudge/domjudge-packaging#115]
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/listinfo/domjudge-devel)
instead of filing an issue here.

### Description of the problem
> Replace this line with a short description.

I try to upload a banner to a contest, contest_id is 3.

But a 500 Internal Server Error occurred.

![image](https://user-images.githubusercontent.com/38343778/144692172-19506353-a966-4a82-9202-7403a74aa731.png)

BTW, I use docker to run domserver.

I checked the user and group to which the corresponding folder belongs.

![image](https://user-images.githubusercontent.com/38343778/144692295-813ef8c4-b4cf-46a5-a206-d2c34b50a199.png)

And I also check the `nginx.conf`.

![image](https://user-images.githubusercontent.com/38343778/144692362-5dee1d3e-7a86-4e85-92a6-b51e64735ed2.png)

So I changed the user group of the `banners` folder, and the upload was successful，like below:

![image](https://user-images.githubusercontent.com/38343778/144692971-a19ae131-1bf8-4206-9b8c-76e04eaf41bf.png)

But if you change the `user` configuration item in `nginx.conf` to `user domjudge;`, it should also be work.

So which kind of change do you think we should make better?

### Your environment
> Include details about your installation here.
> - DOMjudge version (e.g. 7.0.0 or a github commit hash)
> - Operating system / Linux distribution and version (e.g. Ubuntu 18.04)
> - Webserver (e.g. Apache or nginx)

- 8.0.0DEV
- Debian
- Nginx

### Steps to reproduce
> Replace this with a description how we can reproduce your bug.
> - Step 1
> - Step 2
> - Step 3

### Expected behaviour
> Replace this line with what you would expect to happen.

### Actual behaviour
> Replace this line with what happens instead.

### Any other information that you want to share?
> Please include webserver, symfony and judgedaemon log snippets here as appropriate.
> Screenshots may help in case of UI bugs.

**Comment by nickygerritsen** [comment]
I think we should change the folder to www-data or even better use setfacl to add permissions
