### ISSUE TITLE
JudgeHost docker for other languages

### ISSUE THREAD

**Issue by mateuyabar** [DOMjudge/domjudge-packaging#120]
The current docker for judgehost does not support Kotlin either c#. Is there any image with this languages installed?
Thanks,

**Comment by vmcj** [comment]
I think you'll have to build one yourself. So for C# you could add:
https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004-

You could also add this to the chroot in the "official" container by using `dj_run_chroot` and installing there.

**Comment by mateuyabar** [comment]
I'll have it a look. 
I'd just think would be nice to have a docker image for a full judgeHost with everything installed. Otherwise each user has to repeat the same task of modifying the official container

**Comment by nickygerritsen** [comment]
But wat is 'everything'? We can't really create a Docker with the current 22 languages, that feels like a lot of overhead. Why would we ship fortran95 if no one really wants it. The Docker ships with all enabled languages by default and if people want others, they could easily copy https://github.com/DOMjudge/domjudge-packaging/tree/main/docker/judgehost and add their languages there.

**Comment by eldering** [comment]
Also, languages such as C# don't have packages available inside the common Linux distributions, but external repositories, or similar, which make them difficult to setup and maintain.

**Comment by mateuyabar** [comment]
@nickygerritsen Everything was something like the top 10 used?

Ok, just close the issue.
I was trying to avoid "repeated" work.

**Comment by nickygerritsen** [comment]
Note that for non-Docker setups we also offer the `dj_make_chroot` with defaults, which only installs Python 3, java and C/C++. Seems to me it is consistent with that and we offer the option to add languages yourself.

I get that it is a bit repeating, but as eldering said it's also non trivial for us to keep these languages up to date.
