### ISSUE TITLE
Dockerhub Link broken

### ISSUE THREAD

**Issue by jeremy-london** [DOMjudge/domjudge-packaging#129]
On the current domserver and judgehost Docker Hub README the bottom section has a link back to this repo but it is currently broken

I'm not seeing the .md file that generates those READMEs in this repo otherwise i'd make a MR

Problem:
Referencing `master` branch in link instead of `main`

Affects:
- https://hub.docker.com/r/domjudge/domserver/
- https://hub.docker.com/r/domjudge/judgehost/

Current:

```
The source of these images can be found on the [domjudge-packaging GitHub project](https://github.com/DOMjudge/domjudge-packaging/tree/master/docker).
```

Should be 
```
The source of these images can be found on the [domjudge-packaging GitHub project](https://github.com/DOMjudge/domjudge-packaging/tree/main/docker).
```

**Comment by nickygerritsen** [comment]
This is done manually, which I just did. Thanks for reporting!
