### ISSUE TITLE
If I deploy domserver in multiple containers, which directories do I need to mount?

### ISSUE THREAD

**Issue by li1553770945** [DOMjudge/domjudge-packaging#139]
I now want to deploy my domserver in multiple containers. but I have a problem, if I upload the team images in one container, I can't see it in another container because the domserver saves the images inside the container.

I now find that the directories that need to be mounted are `/opt/domserver/webapp/public/images`,this is where the team images are stored, are there any other directories that need to be mounted?

**Comment by nickygerritsen** [comment]
> I now want to deploy my domserver in multiple containers. but I have a problem, if I upload the team images in one container, I can't see it in another container because the domserver saves the images inside the container.
> 
> I now find that the directories that need to be mounted are `/opt/domserver/webapp/public/images`,this is where the team images are stored, are there any other directories that need to be mounted?

Note that that folder might contain some other stuff you might need to copy from the base. Besides that directory we support custom css and JavaScript and those also require two directories under public to be mounted

**Comment by nickygerritsen** [comment]
> > I now want to deploy my domserver in multiple containers. but I have a problem, if I upload the team images in one container, I can't see it in another container because the domserver saves the images inside the container.
> > I now find that the directories that need to be mounted are `/opt/domserver/webapp/public/images`,this is where the team images are stored, are there any other directories that need to be mounted?
> 
> Note that that folder might contain some other stuff you might need to copy from the base. Besides that directory we support custom css and JavaScript and those also require two directories under public to be mounted

Those are webapp/public/{js,css}/custom. And from the image folder copy the domjudge logo SVG

**Comment by li1553770945** [comment]
> > > I now want to deploy my domserver in multiple containers. but I have a problem, if I upload the team images in one container, I can't see it in another container because the domserver saves the images inside the container.
> > > I now find that the directories that need to be mounted are `/opt/domserver/webapp/public/images`,this is where the team images are stored, are there any other directories that need to be mounted?
> > 
> > 
> > Note that that folder might contain some other stuff you might need to copy from the base. Besides that directory we support custom css and JavaScript and those also require two directories under public to be mounted
> 
> Those are webapp/public/{js,css}/custom. And from the image folder copy the domjudge logo SVG

Okay, thanks! I'll do as you say.
