### ISSUE TITLE
Provide a way to name judgehosts

### ISSUE THREAD

**Issue by SolalPirelli** [DOMjudge/domjudge-packaging#14]
Is there a way to name the judgehost when creating the container?

It looks to me like the names are completely random, which is not great when e.g. one judgehost has an issue and you need to figure out which is which.

**Comment by nickygerritsen** [comment]
I think that if you pass `--hostname` to `docker run`, it will use that. Could you verify this?

**Comment by nickygerritsen** [comment]
@SolalPirelli could you confirm passing `--hostname` works?

**Comment by SolalPirelli** [comment]
A bit late, but yes, I confirm.
