### ISSUE TITLE
Supporting additional python libraries

### ISSUE THREAD

**Issue by matko031** [DOMjudge/domjudge-packaging#141]
I am running judgehost in docker container. I would like to allow the participants to use numpy in their submissions.
I have tried running `/opt/domjudge/judgehost/bin/dj_run_chroot` and then `apt install python3-pip && pip3 install numpy` inside the chroot. Everything goes smoothly and `import numpy` in a python shell inside chroot works fine. However, when I upload submission with `import numpy` in it, I still get `ModuleNotFoundError: No module named 'numpy'`

**Comment by vmcj** [comment]
I think it is better to ask for help in (Slack)[https://www.domjudge.org/chat] , as I suspect we will not add numpy to the chroot so will never package a docker container which will have this installed.

**Comment by matko031** [comment]
The issue is not that numpy is not present in the chroot by default, but that when I install it manually, the submissions using numpy still don't work. But I'll ask about it in Slack, thanks!
