### ISSUE TITLE
Error compiling C# problem in Domjudge: 'mcs not found' (able to compile C# files in container, no issues with Java)

### ISSUE THREAD

**Issue by Githector** [DOMjudge/domjudge-packaging#146]
I'm having trouble compiling a C# problem in Domjudge. I'm using Domjudge through the Docker Compose that I found at https://medium.com/@lutfiandri/deploy-domjudge-using-docker-compose-7d8ec904f7b. I've added C# to the list of available languages, but when I try to compile the code, I get the error message 'Compiling failed with exitcode 127, compiler output: /compile-script/run: 23: mcs: not found'. However, I don't have any problems compiling Java code. I have also entered the container and confirmed that I am able to compile C# files without any issues. This leads me to believe that the C# compiler (mcs) may not be installed or accessible on the Domjudge system. Can anyone help me figure out how to install or fix the compiler so I can compile my code successfully?

**Comment by vmcj** [comment]
Hi @Githector,

When you entered the container, did you look in the chroot we use for judging or did you install mcs in the "root" system? Probably you need to install mcs with /opt/domjudge/misc-tools/dj_run_chroot as we judge in a restricted container.

So in case of docker you would have this:
host, running a container for judgehost
   judgehost-container, running the submission inside a restricted container with its own packages

**Comment by Githector** [comment]
Yes!! That was the reason @vmcj ! Thanks!!!
