### ISSUE TITLE
Update Docker base image to bookworm

### ISSUE THREAD

**Issue by tossy310** [DOMjudge/domjudge-packaging#154]
Because I pinned the Docker base image to bullseye (#150) previously, I'm trying to update it to bookworm: https://github.com/tossy310/domjudge-packaging/commit/f9b294b9c391eac5a02049ab8d074382147481b9

This commit includes the following changes:
* Use Python venv to build domserver because Sphinx version should be 6.1.0 or higher to avoid an issue (https://github.com/sphinx-doc/sphinx/issues/11074).
* Use PHP 8.x because it's default in Debian. I think DOMjudge's main branch now no longer supports PHP7. I'm not sure if this script still need to support older DOMjudge that doesn't support PHP8.
* Use libcgoup2 instead of libcgroup1, which is no longer available. libcgroup2 still supports cgroup v1, so this should be okay.

Locally I've successfully built both main branch and 8.2.1 of DOMjudge.

What do you think?

If this looks good, I'm happy to make a PR. Thank you!

**Comment by nickygerritsen** [comment]
We should do this indeed. If we need to release a patch for an older version we can use an older commit so don’t worry about that
