### ISSUE TITLE
Does the domserver image need cgroups?

### ISSUE THREAD

**Issue by SolalPirelli** [DOMjudge/domjudge-packaging#16]
The description of the Docker domserver image suggests giving it access to cgroups, but I don't remember domservers requiring that - am I missing something?

**Comment by nickygerritsen** [comment]
I think you are correct in that domserver doesn't need cgroups. I'll test this out and update the readme if it seems to not be needed.

**Comment by eldering** [comment]
It shouldn't: at least on a plain domserver install you don't need it.
