### ISSUE TITLE
Fix resolv.conf in dockerized judgehost's chroot

### ISSUE THREAD

**Issue by SolalPirelli** [DOMjudge/domjudge-packaging#17]
To download stuff from a dockerized judgehost's chroot, e.g. to use `apt-get`, a proper `/etc/resolv.conf` file is needed.

I fixed this by running `chroot '/chroot/domjudge' /bin/sh -c "echo '$(cat /etc/resolv.conf)' > /etc/resolv.conf"` inside the container, I need to check if this can be automatically done when creating the image though.

**Comment by nickygerritsen** [comment]
Hmmm, I am wondering if running `apt-get` inside the chroot does make sense? Wouldn't it be better to already have the packages installed?

Anyway, I see two possible fixes:

- Mount /etc/resolv.conf from the host in the chroot using a Docker volume
- Modify start.sh to just copy /etc/resolv.conf to the croot

**Comment by eldering** [comment]
I think it makes sense to copy `resolv.conf` and maybe even more from the host or docker image into the chroot inside the image. We do the same with `dj_make_chroot`.
