### ISSUE TITLE
 Judgehost docker container fails to start with latest docker versions

### ISSUE THREAD

**Issue by spitzlei** [DOMjudge/domjudge-packaging#170]
### Description of the problem
Since the update to docker 24.0.7 the judgehost container fails to start. No change in docker 25.0.0

```
judgehost-0-1  | [..] Setting up cgroups
judgehost-0-1  | mkdir: cannot create directory '/sys/fs/cgroup/cpuset/domjudge': Read-only file system
judgehost-0-1  | mkdir: cannot create directory '/sys/fs/cgroup/memory/domjudge': Read-only file system
judgehost-0-1  | chown: cannot access '/sys/fs/cgroup/*/domjudge': No such file or directory
judgehost-0-1  | bin/create_cgroups: 41: cannot create /sys/fs/cgroup/cpuset/domjudge/cpuset.cpus: Directory nonexistent
judgehost-0-1  | bin/create_cgroups: 42: cannot create /sys/fs/cgroup/cpuset/domjudge/cpuset.mems: Directory nonexistent
judgehost-0-1 exited with code 2
```

### Your environment
- Debian Bookworm Host, DOMjudge in docker
- DOMjudge version: domjudge/judgehost:latest

### Steps to reproduce
- Start domserver:latest (site is reachable)
- Start judgehost:latest, like written in hub.docker.com with privileged and `/sys/fs/cgroup:/sys/fs/cgroup:ro`

### Expected behaviour
Judgehosts should run.

### Actual behaviour
Container exits with message above.

**Comment by nickygerritsen** [comment]
We only support cgroups v1 for now and I think your host machine has cgroups v2. Can you follow [these instructions](https://www.domjudge.org/docs/manual/8.2/install-judgehost.html#linux-control-groups) to change back to v1 and see if that works?

**Comment by spitzlei** [comment]
```
cat /proc/cmdline 
BOOT_IMAGE=/vmlinuz-6.1.0-17-amd64 root=/dev/mapper/vg0-root ro systemd.unified_cgroup_hierarchy=0 cgroup_enable=memory swapaccount=1 quiet
```
I'm already running with cgroup v1 (and the system worked like that until the recent docker upgrades from 21.01.2024).

**Comment by nickygerritsen** [comment]
Hmmmm, then we need to investigate... We need to check if they maybe mount the cgroup folder differently.

**Comment by nickygerritsen** [comment]
I had the same issue after upgrading Docker, but https://github.com/DOMjudge/domjudge/pull/2317 seems to fix it. Can you verify by any chance?
