### ISSUE TITLE
installation from live cd

### ISSUE THREAD

**Issue by adiansyahgit** [DOMjudge/domjudge-packaging#2]
excuse me sir, i need this domjudge, is there a way to install domjudge from the live cd?

**Comment by eldering** [comment]
First, this is meant to report bugs, not requests for support. Please use the domjudge-devel mailinglist or IRC for this. Also for followups to this question.

Secondly, it's not clear to me precisely what you mean: do you want to install it on a harddisk, or run from CD/USB? Did you try the instructions in the README and if so, what was the problem?

**Comment by adiansyahgit** [comment]
sorry for  my late replay. i finally found the way to install domjudge live
image to my harddisk.
now is i want to install the domjudge and the judgehost in separate machine.
but the problem is i cant connect the domjudge to the judgehost. the
instruction said:

"the DOMjudge REST API credentials on domserver need to be
synchronized to each judgehost and edited to point to the domserver."

is the /etc/domjudge/restapi.secret the right file??

this is my restapi.secret in judgehost server :

default http://10.10.30.71/domjudge/api domjudge        oP0MRGIegQtV6rJd

10.10.30.71 is the domjudge's ip address.
and 10.10.30.73 is the judgehost's ip address.

im sorry before, im new in github

**Comment by thijskh** [comment]
Please use the domjudge-devel mailinglist for any support requests: https://www.domjudge.org/mailman/listinfo/domjudge-devel
