### ISSUE TITLE
Getting error 500 in a fresh domserver container

### ISSUE THREAD

**Issue by gabrielbiasi** [DOMjudge/domjudge-packaging#21]
I didn't figure out how to solve this. I simply pull the ``domjudge/domserver:latest`` image, mariaDB and run the commands, just copying-and-paste them from https://hub.docker.com/r/domjudge/domserver/.

The ``public`` page shows up normally.
![image](https://user-images.githubusercontent.com/9423868/45260706-20c7f900-b3bc-11e8-9c8e-38bf247510d8.png)

But, if a go to the ``login`` page, I get a 500 code.

![image](https://user-images.githubusercontent.com/9423868/45260680-92ec0e00-b3bb-11e8-827d-846f7d6cc70e.png)

I'm using a Ubuntu 16.04 VM on a Windows 10 host.

Any clue to solve this?

**Comment by nickygerritsen** [comment]
@gabrielbiasi There were some minor issues with the `latest` / `6.0.0` tags with respect to the new way DOMjudge is set up using a Symfony application.

I have fixed these in 59df011 and have pushed new images for the `latest` / `6.0.0` tags.
