### ISSUE TITLE
Update to latest domjudge

### ISSUE THREAD

**Issue by jahirfiquitiva** [DOMjudge/domjudge-packaging#22]
Hello

I was wondering if there's a way that one can upgrade to the latest domjudge. I'm currently using the `2018-01-09` image, which uses domjudge `5.3.2` but I'd like to update to `6.0.1`

Thanks

**Comment by eldering** [comment]
We've not gotten around yet to updating the live images. Once we do (to be honest, I'm not sure when) we'll send an email to the domjudge-annouce list.
