### ISSUE TITLE
How to start judgehost

### ISSUE THREAD

**Issue by jahirfiquitiva** [DOMjudge/domjudge-packaging#23]
Hello

I have installed the live image and entered the option 'domserver & judgehost', but for some reason when I enter the 'judgehosts' option, the server appears offline.

How can I set it to online and working?

Thanks

**Comment by eldering** [comment]
When you choose to boot with the "judgehost" only option, then it is indeed not running a webserver. That's on purpose and meant for when you have one server and multiple other machines running as judgehosts.
Also, please use the emaillist for any further questions and discussions. We like to keep this issue tracker for actual bug reports and feature requests.
