### ISSUE TITLE
Docker: use DOMjudge supplied FPM config and allow to overwrite limits using environment variables

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge-packaging#24]
Currently the Docker image uses the default FPM config shipped with Debian, but we have our own version in the repo. It would be better to use that one, as it has increased limits.

While we are at it, it would be great if we could have an environment variable that will increase `pm.max_children` in the Docker container.

domjudge/domjudge#421 is probably related to this issue, as it reaches the maximum number of children.

**Comment by nickygerritsen** [comment]
@SolalPirelli This might help you with your Docker setup. I have pushed a new 6.0.1 Docker image. The docs on Docker hub are not updated yet, but you can pass `FPM_MAX_CHILDREN=400` to get 400 PHP FPM children.

**Comment by SolalPirelli** [comment]
Awesome, thanks!
