### ISSUE TITLE
Dockerized domserver seems to not be able to write to domserver/tmp

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge-packaging#27]
As reported by @GeniusDex to me, it seems that when you use the domserver Docker image, you can not edit executables. It gives a `permission denied` error for `/opt/domjudge/domserver/tmp` . Changing `TMP_DIR` to `/tmp` seems to work, but we should be able to get the normal path working.

**Comment by nickygerritsen** [comment]
@GeniusDex I just tried with `domserver:latest` and I could edit executables without problem. I also see temp-files in `/opt/domjudge/domserver/tmp`, so was there anything special you did 🤔 ? Like add a volume or something.

**Comment by GeniusDex** [comment]
I followed the steps at https://hub.docker.com/r/domjudge/domserver/ to run the 3 docker containers, using all default values. I just tried to re-create the containers and the problem reproduced.

Host system is running Kubuntu 16.04 with kernel 4.4.0-137-lowlatency.

**Comment by nickygerritsen** [comment]
I will see if at some point I can set up a 16.04 VM to test if it always breaks or if this is some special case for the Kubuntu install of @GeniusDex
