### ISSUE TITLE
Can not run judgehosts

### ISSUE THREAD

**Issue by MohamedQabbani** [DOMjudge/domjudge-packaging#29]
[Feb 28 09:01:57.696] judgedaemon[41]: Judge started on judgedaemon-0-0 [DOMjudge/6.0.3]
[Feb 28 09:01:57.701] judgedaemon[41]: Registering judgehost on endpoint http://domserver/api/v4
[Feb 28 09:01:57.794] judgedaemon[41]: error: Error while executing curl POST to url http://domserver/api/v4/judgehosts: http status code: 401, response:

**Comment by thijskh** [comment]
This means that the u/p you have configured in the judgehost `restapi.secrets` is incorrect. Check that they are the same as configured for the judgehost user in the web interface.

**Comment by MohamedQabbani** [comment]
Thanks

**Comment by kishan-98** [comment]
What if the configuration variable is not found? I tried to run judgedaemon but got response 500 sating a configuration variable "diskspace_error" not found.


![error1](https://user-images.githubusercontent.com/16510667/64005695-801f9b80-cb2e-11e9-9db0-abd17fdbb74d.png)

**Comment by nickygerritsen** [comment]
Hi @kishan-98 . Probably you miss some database update, probably this one: https://github.com/DOMjudge/domjudge/blob/5.3/sql/upgrade/upgrade_5.1.0_5.2.0.sql#L97

Plaase run `sql/dj_setup_database upgrade` as stated in https://www.domjudge.org/docs/admin-manual.html#toc3.19

**Comment by kishan-98** [comment]
> Hi @kishan-98 . Probably you miss some database update, probably this one: https://github.com/DOMjudge/domjudge/blob/5.3/sql/upgrade/upgrade_5.1.0_5.2.0.sql#L97
> 
> Plaase run `sql/dj_setup_database upgrade` as stated in https://www.domjudge.org/docs/admin-manual.html#toc3.19

Thank you for pointing that out! Apparently I couldn't run database upgrade query as I don't have access to domjudge server, so I downgraded my domjudge judgehost verion on my pc and it worked!

**Comment by amitsrivastava1989** [comment]
Getting below error while starting judgehost service

[Aug 14 11:58:07.601] judgedaemon[23244]: Judge started on snu-OptiPlex-3070 [DOMjudge/7.3.0]
[Aug 14 11:58:07.603] judgedaemon[23244]: executing chroot script: 'chroot-startstop.sh check'
[Aug 14 11:58:07.604] judgedaemon[23244]: Registering judgehost on endpoint default: http://10.5.5.59/domjudge/api
[Aug 14 11:58:07.716] judgedaemon[23244]: Registering judgehost on endpoint :
[Aug 14 11:58:07.716] judgedaemon[23244]: error: Argument 1 passed to setup_curl_handle() must be of the type string, null given, called in /home/snu/domjudge/judgehost/lib/judge/judgedaemon.main.php on line 658

**Comment by thijskh** [comment]
@amitsrivastava1989 This is not a support forum. Please ask your questions on the mailinglist or Slack, see https://domjudge.org
