### ISSUE TITLE
judgehosts returns Cgroup, requested group parameter does not exist on problem evaluation

### ISSUE THREAD

**Issue by shukla2112** [DOMjudge/domjudge-packaging#30]
Hi, I am running domServer and domjudgehosts. I am using the latest dockerhub images
-  domjudge/judgehost:6.0.3
- domjudge/domserver:6.0.3

I was able to successfully create the contest, problems on the working setup but on the evaluation of submitted problem, I get the following error.
```shell
Compiling failed with exitcode 255, compiler output:
/opt/domjudge/judgehost/bin/runguard: creating cgroup: Unknown error 50029
Try `/opt/domjudge/judgehost/bin/runguard --help' for more information.
Error: failed to set /sys/fs/cgroup/memory/domjudge/dj_cgroup_1240_1551353391/memory.memsw.limit_in_bytes: Cgroup, requested group parameter does not exist
```

while tried to create Cgroup using the instruction here - https://github.com/DOMjudge/domjudge-packaging/issues/11#issuecomment-373836469

I get the following output - 
```bash
root@judgedaemon-0:/# /opt/domjudge/judgehost/bin/create_cgroups
mount: cpuset is already mounted or /sys/fs/cgroup/cpuset busy
mount: memory is already mounted or /sys/fs/cgroup/memory busy
```

**Comment by nickygerritsen** [comment]
Hmmm I think perhaps your host OS doesn’t understand the cgroups. On what are you running?

**Comment by nickygerritsen** [comment]
Cgroup error 50029 seems to indicate some missing support in the kernel.

I think you need to do this: https://github.com/DOMjudge/domjudge/blob/master/misc-tools/create_cgroups.in#L18

**Comment by shukla2112** [comment]
@nickygerritsen - I have tried running the suggested solution but the error remains same.
I am using ubuntu 14.04 on AWS.

**Comment by nickygerritsen** [comment]
Did you also reboot after applying the setting? If so, it might also be that Ubuntu 14.04 is too old for this support, I'm not sure.

**Comment by meisterT** [comment]
Did you try the suggestion for DigitalOcean/GoogleClous here? https://www.domjudge.org/snapshot/admin-manual/admin-manual-3.html#ss3.7

**Comment by jessegeens** [comment]
Hi,

I'm having trouble with this issue and the link above seems to be broken

**Comment by thijskh** [comment]
@jessegeens That doc is now at https://www.domjudge.org/docs/manual/7.3/install-judgehost.html#linux-control-groups

**Comment by jessegeens** [comment]
Dear @thijskh thanks for that! It doesn't say anything about a specific setup for DigitalOcean though - I'm having trouble running the judgehost docker image as its giving me an error about not having cgroup memory support in the kernel even though I edited the `GRUB_CMDLINE_LINUX_DEFAULT`line, ran update-grub and rebooted

**Comment by eldering** [comment]
@jessegeens Check `/proc/cmdline` to see that grub configuration was actually used when loading the kernel.
Our docs are not aimed at providing specific instructions for particular cloud hosting providers, and this bugreport is not quite the right place to continue debugging this issue, but feel free to ask on our slack channel or the domjudge-devel email list, see https://www.domjudge.org/about.

**Comment by thijskh** [comment]
@jessegeens So just to be sure, you read the part that says “On VM hosting providers such as Google Cloud or DigitalOcean, GRUB_CMDLINE_LINUX_DEFAULT may be overwritten by other files in /etc/default/grub.d/.”?

**Comment by jessegeens** [comment]
Hey guys, sorry for the late reply.
@eldering yes I understand, thanks for the help, I will join the slack channel! :)
@thijskh yeah I saw it, but I didn't find anything else that would overwrite it and found a tweet from DigitalOcean customer support saying that they loaded their kernels by default with `cgroup_enable=memory swapaccount=1`, although it may have been a bit outdated. 
Anyway, as @eldering said, this may not be the correct place to debug this, so I will check out the Slack channel.
