### ISSUE TITLE
Dockerized DOMserver 5.3.3 fails to start because of missing domjudge-fpm.conf

### ISSUE THREAD

**Issue by SolalPirelli** [DOMjudge/domjudge-packaging#35]
First attempt:
> sed: can't read /etc/php/7.0/fpm/pool.d/domjudge.conf: No such file or directory

Next reboots:
> ln: failed to create symbolic link '/etc/php/7.0/fpm/pool.d/domjudge.conf': File exists

This is because `/opt/domjudge/domserver/etc/domjudge-fpm.conf` does not exist in 5.3.3.

BTW, I think the check at https://github.com/DOMjudge/domjudge-packaging/blob/master/docker/domserver/scripts/start.sh#L89 is incorrect, it should be `-L` (check symlink) since the script creates a symlink and not a file.
Sed can be used with `--follow-symlinks` to edit the linked file and not the link itself.

**Comment by nickygerritsen** [comment]
I think it got broken with https://github.com/DOMjudge/domjudge-packaging/commit/05578a72563171f546d20f91d4496aa3b99cf7ea#diff-d8fe8ef1a8a024e2ae388de3bfef4ce4 .
I will try to fix this, but I'm not sure how easy it is to make it work with both 5.x and 6.x

> BTW, I think the check at https://github.com/DOMjudge/domjudge-packaging/blob/master/docker/domserver/scripts/start.sh#L89 is incorrect, it should be -L (check symlink) since the script creates a symlink and not a file.
> Sed can be used with --follow-symlinks to edit the linked file and not the link itself.

Will look into this too, thanks.

**Comment by SolalPirelli** [comment]
Workaround, just in case someone else needs it:

- After `docker run`, add `--entrypoint /bin/sh`
- After the image name, add `-c "sed -i '/^# Remove default FPM/,/^# Set up permissions/d' /scripts/start.sh; /scripts/start.sh"`

Example:

```
sudo docker run --entrypoint /bin/sh \
                --network=net \
                --detach \
                -p 80:80 \
                -p 443:443 \
                --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro \
                -e "CONTAINER_TIMEZONE=Europe/Zurich" \
                -e 'MYSQL_HOST=db' \
                -e 'MYSQL_DATABASE=db' \
                -e 'MYSQL_USER=domjudge' \
                -e 'MYSQL_PASSWORD=domjudge' \
                -e "MYSQL_ROOT_PASSWORD=..." \
                -e 'DJ_DB_INSTALL_BARE=1' \
                domjudge/domserver:5.3.3 \
                -c "sed -i '/^# Remove default FPM/,/^# Set up permissions/d' /scripts/start.sh; /scripts/start.sh"
```

**Comment by nickygerritsen** [comment]
> Workaround, just in case someone else needs it:
> 
> * After `docker run`, add `--entrypoint /bin/sh`
> * After the image name, add `-c "sed -i '/^# Remove default FPM/,/^# Set up permissions/d' /scripts/start.sh; /scripts/start.sh"`
> 
> Example:
> 
> ```
> sudo docker run --entrypoint /bin/sh \
>                 --network=net \
>                 --detach \
>                 -p 80:80 \
>                 -p 443:443 \
>                 --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro \
>                 -e "CONTAINER_TIMEZONE=Europe/Zurich" \
>                 -e 'MYSQL_HOST=db' \
>                 -e 'MYSQL_DATABASE=db' \
>                 -e 'MYSQL_USER=domjudge' \
>                 -e 'MYSQL_PASSWORD=domjudge' \
>                 -e "MYSQL_ROOT_PASSWORD=..." \
>                 -e 'DJ_DB_INSTALL_BARE=1' \
>                 domjudge/domserver:5.3.3 \
>                 -c "sed -i '/^# Remove default FPM/,/^# Set up permissions/d' /scripts/start.sh; /scripts/start.sh"
> ```

Thanks, probably the fix will then be something like:

```
if [ -f /opt/domjudge/domserver/etc/domjudge-fpm.conf ]; then 
  # do what we did before
fi
```

That would work, right? For 6.x our nginx config uses the domjudge-fpm but I think for 5.x it defaults to the debian-supplied one.

**Comment by SolalPirelli** [comment]
Just had to update the workaround (inline, above), the nginx config also needs updating to change which .sock file it should use since `/var/run/php-fpm-domjudge.sock` doesn't exist but `/var/run/php/php7.0-fpm.sock` does.

**Comment by nickygerritsen** [comment]
> Just had to update the workaround (inline, above), the nginx config also needs updating to change which .sock file it should use since `/var/run/php-fpm-domjudge.sock` doesn't exist but `/var/run/php/php7.0-fpm.sock` does.

Ah I thought 5.x didn't use `/var/run/php-fpm-domjudge.sock`. Anyway, I think I have enough info to come up with a proper fix, thanks!

**Comment by nickygerritsen** [comment]
I just pushed new images for `5.3.3` (and also for `6.0.3` to make sure they still work) with the changes in d031c94 😄

**Comment by SolalPirelli** [comment]
Awesome, thanks!
