### ISSUE TITLE
Dockerized judgehost makes it hard to see custom comparer errors

### ISSUE THREAD

**Issue by SolalPirelli** [DOMjudge/domjudge-packaging#36]
```
[Apr 12 17:05:27.345] judgedaemon[36]: Judge started on judge-1-0 [DOMjudge/5.3.3]
[Apr 12 17:05:27.349] judgedaemon[36]: Registering judgehost on endpoint http://<REDACTED>/api
[Apr 12 17:05:27.636] judgedaemon[36]: Found unfinished judging j246 in my name; given back
[Apr 12 17:05:28.157] judgedaemon[36]: Judging submission s26 (endpoint default) (t1/p8/java), id j247...
[Apr 12 17:05:29.136] judgedaemon[36]: Working directory: /opt/domjudge/judgehost/judgings/judge-1-0/endpoint-default/c2-s26-j247
[Apr 12 17:05:31.060] judgedaemon[36]: executing chroot script: 'chroot-startstop.sh start'
[Apr 12 17:05:31.714] testcase_run.sh[169]: Comparing failed with exitcode 255, compare script output:
/opt/domjudge/judgehost/bin/runguard: cannot start `/opt/domjudge/judgehost/judgings/judge-1-0/endpoint-default/executable/Heidi_Learns_Hashing__Easy__cmp/run': No such file or directory
Try `/opt/domjudge/judgehost/bin/runguard --help' for more information.
[Apr 12 17:05:31.723] judgedaemon[36]: error: Unknown exitcode from testcase_run.sh for s26, testcase 1: 1
```

After ignoring the testcase and running bash into the container:

```
root@judge-1:/# ls -lha /opt/domjudge/judgehost/judgings/judge-1-0/endpoint-default/executable/Heidi_Learns_Hashing__Easy__cmp/run
-rwxr-xr-x 1 domjudge domjudge 1.6K Apr 12 16:59 /opt/domjudge/judgehost/judgings/judge-1-0/endpoint-default/executable/Heidi_Learns_Hashing__Easy__cmp/run
```

So clearly the file exists. Not sure what's going on there, investigating...

**Comment by nickygerritsen** [comment]
I assume this is with 5.3.3? Does a non-custom compare script work?

**Comment by SolalPirelli** [comment]
Yes, 5.3.3 and non-custom scripts work fine.

**Comment by SolalPirelli** [comment]
Found the issue, my bash script for the comparer had CRLF instead of just LF, and bash doesn't like that.

Renaming this issue, since the error message from the container is not useful in figuring out the actual error - runguard says the file doesn't exist when it does, but it's invalid. I guess this is also an issue for the main DOMjudge repo - bubble up the error message properly, then make sure it shows in the logs?

Sorry for the not-so-useful report. :/

**Comment by SolalPirelli** [comment]
Also, it'd be helpful if the judgehost container didn't die when this happens, but reported an internal error to the domserver.

**Comment by nickygerritsen** [comment]
We have internal error stuff, but I think it was only introduced in 6.0.

**Comment by SolalPirelli** [comment]
My fault for not updating then... thanks.

**Comment by nickygerritsen** [comment]
What is the reason you need 5.3? Just wondering

**Comment by SolalPirelli** [comment]
I have a bunch of scripts to deploy DOMjudge to Azure automatically: https://github.com/polyprog/azdj
and also some scripts to import teams: https://github.com/PolyProg/contest-scripts

They do weird things with the insides of DOMjudge so I need to port them to 6.0 but I haven't had the time yet.
