### ISSUE TITLE
Problem on supporting python3

### ISSUE THREAD

**Issue by gabrielbiasi** [DOMjudge/domjudge-packaging#38]
I'm getting trouble trying to support python3 using dockerized domjudge.

I'm trying the following sequence in order to "force" install python3 on the judgehost:
```
gabriel@maratona-secomp:~$ docker exec -it secomp-judge-0 bash
root@judgedaemon-0:/# cd /opt/domjudge/judgehost/bin
root@judgedaemon-0:/opt/domjudge/judgehost/bin# ./dj_run_chroot 
Entering chroot in '/chroot/domjudge'.
# python3         
/bin/sh: 1: python3: not found
# apt-get install python3
Reading package lists... Done     
[apt-get output removed by me]
Processing triggers for libc-bin (2.24-11+deb9u4) ...
# python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
# exit
Exited chroot in '/chroot/domjudge'.
root@judgedaemon-0:/opt/domjudge/judgehost/bin# exit
exit
```

Even after this I can't judge a python script, I'm getting:
```
Compiling failed with exitcode 127, compiler output:
/opt/domjudge/judgehost/judgings/judgedaemon-0-0/endpoint-default/executable/py3/run: 20: /opt/domjudge/judgehost/judgings/judgedaemon-0-0/endpoint-default/executable/py3/run: python3: not found
```

Any clue about this case?

**Comment by nickygerritsen** [comment]
Hi @gabrielbiasi !
Besides needing `python3` inside the chroot, we also need it **outside** the chroot for a syntax check on the code. Can you try to also install it in the Docker image directly?

**Comment by gabrielbiasi** [comment]
Oh gosh... I was so focused in the chroot environment and I didn't try to install outside.
It worked, thank you.

**Comment by verngutz** [comment]
I'm trying to upgrade pypy3 using the same process. I can run pypy3 both inside the chroot environment and outside, but compiling through the interface gives me:
```
Compiling failed with exitcode 127, compiler output:
Info: detected entry_point: 
/compile-script/run: 26: pypy3: not found
```
What else did I miss?

**Comment by vmcj** [comment]
> I'm trying to upgrade pypy3 using the same process. I downloaded the linux binaries from https://www.pypy.org/download.html, unzipped, and replaced the pypy3 symlink in /usr/bin (inside the chroot environment) to point to the unzipped pypy3. I can run pypy3 both inside the chroot environment and outside, but compiling through the interface gives me:
> 
> ```
> Compiling failed with exitcode 127, compiler output:
> Info: detected entry_point: 
> /compile-script/run: 26: pypy3: not found
> ```
> 
> What else did I miss?

Hi @verngutz, you're responding to an older issue. Can you ask this in Slack? I think more people can help you there. Issues are not used to help with specific instances only for bugs in the current codebase.
