### ISSUE TITLE
the docker image pulled from the hub has the same password. 

### ISSUE THREAD

**Issue by tabris233** [DOMjudge/domjudge-packaging#40]
Now the docker image pulled from the hub has the same password. 
It's also unsafe. 
We may need to set the admin_password when generating the docker container.

excuse for my poor english.

**Comment by nickygerritsen** [comment]
I noticed this as well. We generate the password during the install, but this is done when building the image.

We might want to call the generate command again upon first startup of the container

**Comment by nickygerritsen** [comment]
This has been fixed with the images of 7.0.2, which will be pushed in a minute.
