### ISSUE TITLE
Debian packaged `domjudge-judgehost.init` has wrong cgroup dir

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge-packaging#41]
See https://github.com/DOMjudge/domjudge/issues/617: the file `debian/domjudge-judgehost.init` is out of date and contains `CGROUPDIR=/cgroup` which should point to `/sys/fs/cgroup`. This fails at least on Debian 10 Buster.

**Comment by thijskh** [comment]
Likely better to replace it with a systemd unit?
