### ISSUE TITLE
Docker build fials: mcrypt deprecation

### ISSUE THREAD

**Issue by dodedodo33** [DOMjudge/domjudge-packaging#42]
Trying to build a docker image right now fails due to mcrypt being deprecated in php 7.2+. The current debian:latest has php 7.3.4.

I'm working on the dockerfiles to include the mcrypt extension from pecl.

But this made me think: Are there any other potential issues with php 7.3?

**Comment by nickygerritsen** [comment]
I wonder if we actually need mcrypt...

**Comment by thijskh** [comment]
We don't. You can just remove it.

At some point in the past it was listed in the admin manual because it was a soft dependency of phpMyAdmin.

**Comment by thijskh** [comment]
As for @dodedodo33's question: we have several installations with PHP 7.3, no problems have been found yet (in DOMjudge - there was a bug in a specific PHP version so be sure to use the latest, PHP 7.3.9).

**Comment by nickygerritsen** [comment]
I will remove it from the dockerfile soon

**Comment by dodedodo33** [comment]
Awesome, I'll give it a go without mcrypt :)
