### ISSUE TITLE
7.1.1 Docker Domserver Invalid credentials for admin/admin

### ISSUE THREAD

**Issue by bumfo** [DOMjudge/domjudge-packaging#47]
### Description of the problem
> The default password described in docker document is invalid for domserver 7.1.1 on docker

### Your environment
> Include details about your installation here.
> - DOMjudge version 7.1.1
> - Operating system Windows 10 Docker
> -  nginx

### Steps to reproduce
> Replace this with a description how we can reproduce your bug.
> - Follow the steps at https://hub.docker.com/r/domjudge/domserver/
> - Open localhost:12345/login
> - Try to login with admin/admin as described in the tutorial, 

### Expected behaviour
> successfully login. 

### Actual behaviour
> get Invalid credentials.

### Any other information that you want to share?
> domserver:latest

**Comment by nickygerritsen** [comment]
Yes the documentation is indeed outdated. I will update it.
