### ISSUE TITLE
Hash Sum Mismatch

### ISSUE THREAD

**Issue by bredereck** [DOMjudge/domjudge-packaging#6]
When trying to update, I get:
Err:7 https://domjudge.org/debian unstable/ domjudge-common 5.3.2-1", "  Hash Sum mismatch"
(I cleaned the apt cache before)

**Comment by eldering** [comment]
Fixed. This was due to an issue in `mini-dinstall` when regenerating the package hashes, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=680782
