### ISSUE TITLE
judgehost docker image: REST api file for DOMjudge v5.3.2

### ISSUE THREAD

**Issue by miguelmartin75** [DOMjudge/domjudge-packaging#8]
Not sure if I missed a step during installation of the docker image for judgehost, but with the rest API file as this:

    echo "default	${DOMSERVER_BASEURL}api/v4	${JUDGEDAEMON_USERNAME}	${JUDGEDAEMON_PASSWORD}" > etc/restapi.secret

The judgehost will fail with the following error message:

    [Feb 12 14:50:11.021] judgedaemon[29]: error: Error while executing curl POST to url http://domserver/api/v4/judgehosts: http status code: 400, response: {"error":"Function 'v4\/judgehosts#POST' does not exist."}

To fix it, I simply removed `/v4` from the REST api url.

I built the containers with the `build.sh` script, like so:

    ./build.sh 5.3.2

**Comment by nickygerritsen** [comment]
Ah yes the /v4 thing is new for 6.0, which is not released yet. I’ll push a fix tonight (CET) and create new Docker images.

**Comment by nickygerritsen** [comment]
I have just pushed a fix. A new Docker image for the judgehost has been pushed to the Docker Hub as well.
