### ISSUE TITLE
Dockerized DOMjudge can't read dbpasswords.secret

### ISSUE THREAD

**Issue by SolalPirelli** [DOMjudge/domjudge-packaging#9]
Running the following (where `db` is a healthy MySQL docker image, `net` is a Docker network, and the MYSQL_* parameters are all valid):

```
sudo docker run --name=server \
                --network=net \
                -it --detach \
                -p 80:80 \
                --restart=always \
                --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro \
                -e 'CONTAINER_TIMEZONE=Europe/Zurich' \
                -e 'MYSQL_HOST=db' \
                -e 'MYSQL_DATABASE=db' \
                -e 'MYSQL_USER=domjudge' \
                -e 'MYSQL_PASSWORD=domjudge' \
                -e 'MYSQL_ROOT_PASSWORD=root_password' \
                -e 'DJ_DB_INSTALL_BARE=1' \
                domjudge/domserver:5.3.2
```

results in a DOMjudge that always returns an HTTP 500; nginx's log indicates `Cannot read database credentials file /opt/domjudge/domserver/etc/dbpasswords.secret in /opt/domjudge/domserver/lib/use_db.php on line 11`.

`chmod 644 /opt/domjudge/domserver/etc/dbpasswords.secret`, i.e. make the file world-readable, fixes the issue.

**Comment by nickygerritsen** [comment]
Hmmm, it should set ACL's for this file:

```bash
setfacl    -m   u:www-data:r    etc/dbpasswords.secret > /dev/null 2>&1 || true
setfacl    -m   u:www-data:r    etc/restapi.secret > /dev/null 2>&1 || true
```

Could you check in the docker-container what `getfacl /opt/domjudge/domserver/etc/dbpasswords.secret` returns?

**Comment by SolalPirelli** [comment]
```
getfacl: Removing leading '/' from absolute path names
# file: opt/domjudge/domserver/etc/dbpasswords.secret
# owner: domjudge
# group: domjudge
user::rw-
group::r--
other::---
```
(the "other" becomes `r--` after my chmod)

**Comment by SolalPirelli** [comment]
Running the `setfacl` from the script you pasted, from `/opt/domjudge/domserver`, returns 1 and prints `setfacl: etc/dbpasswords.secret: Operation not supported`.

**Comment by nickygerritsen** [comment]
Are you using a special volume driver for Docker?

**Comment by SolalPirelli** [comment]
Nothing special, I'm on the default Ubuntu 16.04 VM in Azure, and installed Docker via `sudo apt-get install --no-install-recommends -y docker.io`. I'll look into how to enable ACLs...

**Comment by nickygerritsen** [comment]
OK let me know. Another option would be to chown the file as www-data, but I'm not sure if that works. (or chmod'ing but I'd prefer not to do that)

**Comment by SolalPirelli** [comment]
Thanks a lot for the fast replies! 👍 

`echo '{ "storage-driver": "devicemapper" }' | sudo tee /etc/docker/daemon.json` and restarting Docker fixes the problem, since `devicemapper` supports ACLs.

The [docker documentation](https://docs.docker.com/storage/storagedriver/select-storage-driver/) on storage drivers indicates that `devicemapper` is pretty far down in the priority list, so I'm a bit surprised this problem hasn't occurred to other people yet.

Why `> /dev/null 2>&1 || true`, though? Makes it harder to debug a problem like this.

**Comment by nickygerritsen** [comment]
The `> /dev/null 2>&1 || true` was there especially for the contributor image, as this uses a volume mount, which on Windows and macOS don't support ACL's, but also don't need it.
In the normal image it would be better if we remove it.

I think replacing ACL's with just a `chown www-data:` should do the trick as well. Could you test if this works without using devicemapper? If so, I'll push an update.

**Comment by SolalPirelli** [comment]
```diff
diff --git a/docker/domserver/scripts/start.sh b/docker/domserver/scripts/start.sh
index ef0ed54..590f862 100644
--- a/docker/domserver/scripts/start.sh
+++ b/docker/domserver/scripts/start.sh
@@ -76,8 +76,8 @@ cp etc/nginx-conf /etc/nginx/sites-enabled/default
 sed -i 's/server unix:.*/server unix:\/run\/php\/php7.0-fpm.sock;/' /etc/nginx/sites-enabled/default

 # Set up permissions
-setfacl    -m   u:www-data:r    etc/dbpasswords.secret > /dev/null 2>&1 || true
-setfacl    -m   u:www-data:r    etc/restapi.secret > /dev/null 2>&1 || true
+chown www-data: etc/dbpasswords.secret
+chown www-data: etc/restapi.secret

 if [[ "${USE_LEGACY}" -eq "0" ]]
 then
```

indeed works fine with storage driver `overlay2` (default on my VM). Not sure what to do about the other `setfacl` calls further down the script, though.

**Comment by nickygerritsen** [comment]
Great, I'll have a look and push an update! Thanks for testing.
