### ISSUE TITLE
Error: cgroup support missing memory features in running kernel

### ISSUE THREAD

**Issue by giampq** [DOMjudge/domjudge-packaging#92]
Hi guys, i have a issue when start Judgehost on Ubuntu 

----------------------------------------
[..] Setting timezone

Current default time zone: 'Europe/Amsterdam'
Local time is now:      Thu Jun 10 03:12:20 CEST 2021.
Universal Time is now:  Thu Jun 10 01:12:20 UTC 2021.

[ok] Container timezone set to: Europe/Amsterdam

[..] Setting up restapi file
[ok] Restapi file set up

[..] Setting up cgroups
Error: cgroup support missing memory features in running kernel. Unable to continue.

    To fix this, please make the following changes:
    1. In /etc/default/grub, add 'cgroup_enable=memory swapaccount=1' to GRUB_CMDLINE_LINUX_DEFAULT
----------------------------------------

Please help me fix it, thank

**Comment by mvr320** [comment]
Hi @giampq,
The solution is here to in the host its grub alter the fix you mentioned. The docker container uses the kernel from the host so the host should have the cgroup support which is needed.

If you have additional questions could you ask them on the Slack (https://www.domjudge.org/chat) as this is not really a bug so more people might be able to help you there.
