### ISSUE TITLE
Fix docker build for domjudge 7.3

### ISSUE THREAD

**Issue by incaseoftrouble** [DOMjudge/domjudge-packaging#94]
Domjudge 7.3 updated to php 7.4, the start.sh / php-fpm however has a hardcoded php version, the built docker image fails to start

I'll provide a PR tomorrow (its only a few changes).

If it's ok, I'll also add `make dist` to the `build.sh` - then one can directly use local sources without needing to install all the dependencies for it (they are present in the dockerfile anyway)

**Comment by nickygerritsen** [comment]
Thanks, a PR sounds good!
